const actionTypes = {
  LOGIN: "LOGIN",
  CHANGE_WINDOW: "CHANGE_WINDOW",
  SAVE_CONTACTS: "SAVE_CONTACTS",
  SAVE_CAMPAIGNS: "SAVE_CAMPAIGNS",
  TOGGLE_MODAL: "TOGGLE_MODAL",
};

export default actionTypes;
