const actionTypes = {
  LOGIN: "LOGIN",
  CHANGE_WINDOW: "CHANGE_WINDOW",
  SAVE_CONTACTS: "SAVE_CONTACTS",
  SAVE_CAMPAIGNS: "SAVE_CAMPAIGNS",
  SAVE_TAGS: "SAVE_TAGS",
  TOGGLE_MODAL: "TOGGLE_MODAL",
  FETCH_CONTACT: "FETCH_CONTACT",
  UPDATE_CONTACT: "UPDATE_CONTACT"
};

export default actionTypes;
