const actionTypes = {
  LOGIN: "LOGIN",
  CHANGE_WINDOW: "CHANGE_WINDOW",
  SAVE_CONTACTS: "SAVE_CONTACTS",
  SAVE_CAMPAIGNS: "SAVE_CAMPAIGNS",
  SAVE_TAGS: "SAVE_TAGS",
  TOGGLE_MODAL: "TOGGLE_MODAL",
  FETCH_CONTACT: "FETCH_CONTACT",
  UPDATE_CONTACT: "UPDATE_CONTACT",
  FETCH_NOTIFICATIONS: "FETCH_NOTIFICATIONS",
  UPDATE_NOTIFICATIONS: "UPDATE_NOTIFICATIONS",
  SET_NEW_NOTIFICATION: "SET_NEW_NOTIFICATION",
  CONFIRMATION_MODAL: "CONFIRMATION_MODAL",
  SAVE_SELECTED_PLAN: "SAVE_SELECTED_PLAN",
  SAVE_STRIPE_SECRET: "SAVE_STRIPE_SECRET",
};

export default actionTypes;
